project:
  type: website

website:
  title: "NBA FT%"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - model.qmd
      - sources.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



